/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AntIcon: typeof import('./../src/components/ant-icon/index.vue')['default']
    copy: typeof import('./../src/components/mine-button/index copy.vue')['default']
    MineButton: typeof import('./../src/components/mine-button/index.vue')['default']
    MineHeader: typeof import('./../src/components/mine-header/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../src/components/side-bar/index.vue')['default']
  }
}
